version: "3.7"
services:
   redis:
      image: redis:latest
      restart: unless-stopped
      network_mode: bridge
      expose:
        - 6379
   api:
    build: .
    container_name: api
    restart: unless-stopped
    network_mode: bridge
    command: /bin/sh -c 'nodemon -e js.html app.js'
    ports:
      - 8090:9000
    volumes:
      - .:/src
      - /src/node_modules
    links:
      - redis
